### ISSUE TITLE
Question on intent, deliverable in this REPO

### ISSUE THREAD

**Issue by gshanemiller** [lorin/tla-linearizability#1]
Hi,

In my own work I am trying to use TLA+/TLC to define linearizability, which you've already done in GIT for all to see.

Now aside from bringing Herlihy's definitions into TLA+ and exercising operators over hardcoded lists of operations/responses, a TLA model ideally would check a particular implementation of a FIFO queue, and prove it implements linearizability. Importantly, any implementation would not use atomic sequences thereby hiding in TLA a more complicated implementation detail. It would faithfully implement atomic operations (integer operations) or faithfully model CAS if that was important to the implementation.

May in respectfully inquire if that was your intent? This something Herlihy turns to in section 4.

**Comment by lorin** [comment]
I did this just as an intellectual exercise.

The definition of linearizability that I use in this repo is not very practical for use in checking whether a particular model satisfies linearizability. 

For a more practical example, see https://www.microsoft.com/en-us/research/video/tla-specifications-of-the-consistency-guarantees-provided-by-cosmos-db/
